# Tokenisation & Stopword Removal 

In [29]:

document="""It was a very pleasant day. The weather was cool and there were light showers. I went to the market to buy some fruits."""
sentence ="Send all the 50 documents related to chapter 1,2,3 at prateek@cb.com"


In [30]:
from nltk.tokenize import sent_tokenize,word_tokenize


In [31]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

#converting the document into sentences

In [32]:

sents=sent_tokenize(document)
print(sents)
print(len(sents))

['It was a very pleasant day.', 'The weather was cool and there were light showers.', 'I went to the market to buy some fruits.']
3


In [33]:
sents[0]

'It was a very pleasant day.'

#spliting the sentences into words

In [34]:

sentence.split()

['Send',
 'all',
 'the',
 '50',
 'documents',
 'related',
 'to',
 'chapter',
 '1,2,3',
 'at',
 'prateek@cb.com']

In [35]:
#using word tokenize function 
words=word_tokenize(sentence)
words

['Send',
 'all',
 'the',
 '50',
 'documents',
 'related',
 'to',
 'chapter',
 '1,2,3',
 'at',
 'prateek',
 '@',
 'cb.com']

#removing the stopword

In [36]:

nltk.download('stopwords')
from nltk.corpus import stopwords
sw=set (stopwords.words('english'))
print(sw)#comman stopword in english 

{"weren't", 'their', 'just', 'between', 'until', "you'll", 'does', 'because', 'mightn', 'be', 'ourselves', 'for', 'couldn', 'while', "should've", 'than', 'having', 'up', 'hasn', 't', 'themselves', 'shan', 'wouldn', 'll', 'the', 'all', "shan't", 'out', 'theirs', 'in', "hasn't", 'too', "that'll", 'i', 'through', 'an', 'of', 'these', 'y', 'then', 'weren', "needn't", 'ain', "don't", 'myself', 've', 'is', 'were', 'she', "wouldn't", 'most', 'other', 'who', 'did', 'herself', 'been', 'won', 'what', 'each', 'yours', 'himself', 'do', 'here', 'now', 'we', 'hers', "you'd", 'again', 'after', 'my', 'was', 'can', "couldn't", 'by', 'm', 'o', "it's", 'has', 'not', 'am', "wasn't", 'so', "hadn't", 'very', 'itself', "mustn't", "shouldn't", 'or', "won't", 'ours', 'don', 'which', 'below', 'hadn', 'd', 'further', 'where', "she's", "you've", 'a', 'aren', 'didn', 'ma', 'if', 'to', "doesn't", 'you', 'into', 'our', "aren't", 'its', 'during', 'your', 'against', 'doesn', 'doing', 'as', 'same', 'those', "haven't", 

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [37]:
def remove_stopwords(text,stopwords):
  useful_words=[w for w in text if w not in stopwords]
  return useful_words

In [38]:
text ="i am not bothered about her very much ".split()
useful_text=remove_stopwords(text ,sw)
print(useful_text)#remove all the stopword and printing all useful word

['bothered', 'much']


#TOKENIZATION USING REGULAR EXPRESSION

In [39]:
 
#regex tester wesite (for regular expression)
sentence ="Send all the 50 documents related to chapter 1,2,3 at prateek@cb.com"


In [40]:
sentence.split()

['Send',
 'all',
 'the',
 '50',
 'documents',
 'related',
 'to',
 'chapter',
 '1,2,3',
 'at',
 'prateek@cb.com']

In [41]:
from nltk.tokenize import RegexpTokenizer


In [42]:
tokenize=RegexpTokenizer('[a-zA-Z@.]+')
useful_text=tokenize.tokenize(sentence)
useful_text

['Send',
 'all',
 'the',
 'documents',
 'related',
 'to',
 'chapter',
 'at',
 'prateek@cb.com']

#Stemming 

->process that transform particular words (verbs ,plurals )into their redical form
->preserve the semantics of the sentence without increasing the number of unique tokenize
->Example-jupms ,jumpig ,jumped,jump ==>jump

In [43]:
text ="""Foxes love to make jumps .The quick brown fox was seem jumping over the lovely dog from a 6ft feet high wall """


In [44]:
#Snowball Stemmer ,Porter ,Lancaster Stemmer 
from nltk.stem.snowball import SnowballStemmer,PorterStemmer
from nltk.stem.lancaster import LancasterStemmer


In [45]:
ps=PorterStemmer()

In [46]:
ps.stem('jumping')

'jump'

In [47]:
ps.stem('loving')

'love'

In [48]:
 #snowball stemmer 
 ss=SnowballStemmer('english')
 

In [49]:
ss.stem('lovely')

'love'

In [50]:
ss.stem('jumping')

'jump'

In [51]:
#Lemmanization (doing same as stemming )
import nltk
nltk.download('wordnet')
from nltk.stem import WordNetLemmatizer


[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [52]:
wn =WordNetLemmatizer()
wn.lemmatize('working')

'working'

BUILDING A VOCAB & VECTORIZATION

In [72]:
corpus=['Indian cricket team will wins world cup,says capt. Virat kohli .World cup will be held at Sri Lanka .',
        'we will win next lok sabha Elections ,says confident indian PM.',
        'the nodel laurate won the hearts of the people.',
        'the movie Raazi is an exciting Indian spy thrillar based upon a real story.']

In [54]:
from sklearn.feature_extraction.text import CountVectorizer


In [73]:
cv=CountVectorizer()


In [74]:
vecotrized_corpus=cv.fit_transform(corpus)#conver corpus into vector (mean in the form of 0,1,0...........)bassically it will tak e
vecotrized_corpus

<4x42 sparse matrix of type '<class 'numpy.int64'>'
	with 47 stored elements in Compressed Sparse Row format>

In [75]:
import numpy as np
vecotrized_corpus = vecotrized_corpus.toarray()


In [80]:
vecotrized_corpus[0]

array([0, 1, 0, 1, 1, 0, 1, 2, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 2, 0, 1, 0, 2])

In [77]:
len(vecotrized_corpus[0])

42

In [71]:
print (cv.vocabulary_)

{'indian': 9, 'cricket': 3, 'team': 26, 'wins': 31, 'world': 32, 'cup': 4, 'says': 22, 'capt': 1, 'virat': 29, 'kohli': 10, 'held': 8, 'sri': 24, 'lanka': 11, 'win': 30, 'next': 15, 'lok': 13, 'sabha': 21, 'elections': 5, 'confident': 2, 'pm': 18, 'nodel': 16, 'laurate': 12, 'hearts': 7, 'people': 17, 'movie': 14, 'raazi': 19, 'exciting': 6, 'spy': 23, 'thrillar': 27, 'based': 0, 'upon': 28, 'real': 20, 'story': 25}


In [70]:
 cv.vocabulary_ #vacab is a list which contian unique words which is obtain by doing above process.

{'indian': 9,
 'cricket': 3,
 'team': 26,
 'wins': 31,
 'world': 32,
 'cup': 4,
 'says': 22,
 'capt': 1,
 'virat': 29,
 'kohli': 10,
 'held': 8,
 'sri': 24,
 'lanka': 11,
 'win': 30,
 'next': 15,
 'lok': 13,
 'sabha': 21,
 'elections': 5,
 'confident': 2,
 'pm': 18,
 'nodel': 16,
 'laurate': 12,
 'hearts': 7,
 'people': 17,
 'movie': 14,
 'raazi': 19,
 'exciting': 6,
 'spy': 23,
 'thrillar': 27,
 'based': 0,
 'upon': 28,
 'real': 20,
 'story': 25}

In [78]:
len(cv.vocabulary_.keys())

42

In [63]:
#Revers mapping 
numbers = vecotrized_corpus[2]
print(numbers)#this is vocab in numbers form  
reshaped_numbers = numbers.reshape(1, -1)

[0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 3 0 0 0 0
 0 0 0 1 0]


In [64]:
#converting the numbers into word or vocab
cv.inverse_transform(reshaped_numbers)

[array(['hearts', 'laurate', 'nodel', 'of', 'people', 'the', 'won'],
       dtype='<U9')]

Vectorization with stopward Removal

In [65]:

# !pip install Tokenizer
def myTokenizer(document):
    tokenizer = RegexpTokenizer(r'\w+')
    words = tokenizer.tokenize(document.lower())
    words=remove_stopwords(words,sw)
    return words

In [66]:
myTokenizer("this is some function ")

['function']

In [67]:
myTokenizer(sentence)

['send',
 '50',
 'documents',
 'related',
 'chapter',
 '1',
 '2',
 '3',
 'prateek',
 'cb',
 'com']

In [68]:
cv=CountVectorizer(tokenizer=myTokenizer)
vecotrized_corpus=cv.fit_transform(corpus).toarray()
print(vecotrized_corpus)
print(len(vecotrized_corpus[0]))
#the length is less than preivious method ........so tokenization is a preffrable method


[[0 1 0 1 2 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 1 0 1 2]
 [0 0 1 0 0 1 0 0 0 1 0 0 0 1 0 1 0 0 1 0 0 1 1 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0 0 0 1 1 0 0 1 0 1 0 1 1 0 0 0 0]]
33


/usr/local/lib/python3.10/dist-packages/sklearn/feature_extraction/text.py:528: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


In [69]:
#lets see the inverse of vectorize numbers ...it wil be in vacab form
cv.inverse_transform(vecotrized_corpus)

[array(['capt', 'cricket', 'cup', 'held', 'indian', 'kohli', 'lanka',
        'says', 'sri', 'team', 'virat', 'wins', 'world'], dtype='<U9'),
 array(['confident', 'elections', 'indian', 'lok', 'next', 'pm', 'sabha',
        'says', 'win'], dtype='<U9'),
 array(['hearts', 'laurate', 'nodel', 'people'], dtype='<U9'),
 array(['based', 'exciting', 'indian', 'movie', 'raazi', 'real', 'spy',
        'story', 'thrillar', 'upon'], dtype='<U9')]

In [84]:
#for the test data
test_corpus=[
    'Indian cricket rock!'
]

In [86]:
cv.fit_transform( test_corpus).toarray()

array([[1, 1, 1]])

In [87]:
cv.vocabulary_

{'indian': 1, 'cricket': 0, 'rock': 2}

#MORE WAYS TO CREATE FEATURES



UNIGRAM->every word taking as a Feature #simple way
BIGRAM 
TRIGRAMS 
N-GRAMS 
TF-IDF NORMALIZATION 


In [ ]:
sent_1=['this is good movie']
sent_2=['this is good movie but actor is not present ']
sent_3=['this is not good movie']

In [90]:
sent_1=['this is good movie']
sent_2=['this is not good movie']

#here both sentence almost same if we avoid 'not'...so this type of confusion can create a problem for classifier.


In [100]:
cv = CountVectorizer(ngram_range=(2,2))#ngram convert the word into bigram or trigram ....mean combine the words


In [101]:
docs=[sent_1[0],sent_2[0]]
cv.fit_transform(docs).toarray()

array([[1, 1, 0, 0, 1],
       [1, 0, 1, 1, 1]])

In [102]:
cv.vocabulary_

{'this is': 4, 'is good': 1, 'good movie': 0, 'is not': 2, 'not good': 3}

#TF -IDF NORMALIZATION 

##->Avoid features that occurs very often,becauase they contains less information
##->Information decreases as the numbers of occurences increases across different type of document 
##->so we define another term-term document-frequency which associates a weight with every word

In [103]:
from nltk.corpus.reader.sentiwordnet import SentiSynset
#full form ->term frequency(how many time a word appears across the sentence) -inverse document frequency(how many time the word appears across the corpus )

sent_1="this is good movie"
sent_2="this was good movie"
sent_3="this is not good movie"
corpus=[sent_1,sent_2,sent_3]

In [104]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()

In [106]:
vc=tfidf.fit_transform(corpus).toarray()
print(vc)

[[0.46333427 0.59662724 0.46333427 0.         0.46333427 0.        ]
 [0.41285857 0.         0.41285857 0.         0.41285857 0.69903033]
 [0.3645444  0.46941728 0.3645444  0.61722732 0.3645444  0.        ]]


In [108]:
tfidf.vocabulary_ #in third the word not is higher frequency  

{'this': 4, 'is': 1, 'good': 0, 'movie': 2, 'was': 5, 'not': 3}